// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/gateway/v1/gateway.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Images        []string               `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

type Tool struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchemaJson string                 `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	ToolsJson     string                 `protobuf:"bytes,2,opt,name=tools_json,json=toolsJson,proto3" json:"tools_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ListToolsResponse) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ListToolsResponse) GetToolsJson() string {
	if x != nil {
		return x.ToolsJson
	}
	return ""
}

type ToolExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	InputJson     string                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecutionRequest) Reset() {
	*x = ToolExecutionRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionRequest) ProtoMessage() {}

func (x *ToolExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionRequest.ProtoReflect.Descriptor instead.
func (*ToolExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ToolExecutionRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolExecutionRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ToolExecutionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ToolExecutionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson      string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,4,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolExecutionResponse) Reset() {
	*x = ToolExecutionResponse{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionResponse) ProtoMessage() {}

func (x *ToolExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionResponse.ProtoReflect.Descriptor instead.
func (*ToolExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ToolExecutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolExecutionResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolExecutionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolExecutionResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type ListMCPToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMCPToolsRequest) Reset() {
	*x = ListMCPToolsRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMCPToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMCPToolsRequest) ProtoMessage() {}

func (x *ListMCPToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMCPToolsRequest.ProtoReflect.Descriptor instead.
func (*ListMCPToolsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

type ToolList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolList) Reset() {
	*x = ToolList{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolList) ProtoMessage() {}

func (x *ToolList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolList.ProtoReflect.Descriptor instead.
func (*ToolList) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *ToolList) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ListMCPToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolsByServer map[string]*ToolList   `protobuf:"bytes,1,rep,name=tools_by_server,json=toolsByServer,proto3" json:"tools_by_server,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMCPToolsResponse) Reset() {
	*x = ListMCPToolsResponse{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMCPToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMCPToolsResponse) ProtoMessage() {}

func (x *ListMCPToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMCPToolsResponse.ProtoReflect.Descriptor instead.
func (*ListMCPToolsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *ListMCPToolsResponse) GetToolsByServer() map[string]*ToolList {
	if x != nil {
		return x.ToolsByServer
	}
	return nil
}

// Persona management messages
type PersonaMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonaName   string                 `protobuf:"bytes,1,opt,name=persona_name,json=personaName,proto3" json:"persona_name,omitempty"`
	Intent        string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonaMetadata) Reset() {
	*x = PersonaMetadata{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonaMetadata) ProtoMessage() {}

func (x *PersonaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonaMetadata.ProtoReflect.Descriptor instead.
func (*PersonaMetadata) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *PersonaMetadata) GetPersonaName() string {
	if x != nil {
		return x.PersonaName
	}
	return ""
}

func (x *PersonaMetadata) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *PersonaMetadata) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *PersonaMetadata) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type GetPersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonaRequest) Reset() {
	*x = GetPersonaRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonaRequest) ProtoMessage() {}

func (x *GetPersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonaRequest.ProtoReflect.Descriptor instead.
func (*GetPersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{12}
}

type IntentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Template      string                 `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentConfig) Reset() {
	*x = IntentConfig{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentConfig) ProtoMessage() {}

func (x *IntentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentConfig.ProtoReflect.Descriptor instead.
func (*IntentConfig) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *IntentConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IntentConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *IntentConfig) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

type PersonaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CanHandle     []string               `protobuf:"bytes,4,rep,name=can_handle,json=canHandle,proto3" json:"can_handle,omitempty"`
	CannotHandle  []string               `protobuf:"bytes,5,rep,name=cannot_handle,json=cannotHandle,proto3" json:"cannot_handle,omitempty"`
	Intents       []*IntentConfig        `protobuf:"bytes,6,rep,name=intents,proto3" json:"intents,omitempty"`
	TextModel     string                 `protobuf:"bytes,7,opt,name=text_model,json=textModel,proto3" json:"text_model,omitempty"`
	VisionModel   string                 `protobuf:"bytes,8,opt,name=vision_model,json=visionModel,proto3" json:"vision_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonaResponse) Reset() {
	*x = PersonaResponse{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonaResponse) ProtoMessage() {}

func (x *PersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonaResponse.ProtoReflect.Descriptor instead.
func (*PersonaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *PersonaResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonaResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PersonaResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PersonaResponse) GetCanHandle() []string {
	if x != nil {
		return x.CanHandle
	}
	return nil
}

func (x *PersonaResponse) GetCannotHandle() []string {
	if x != nil {
		return x.CannotHandle
	}
	return nil
}

func (x *PersonaResponse) GetIntents() []*IntentConfig {
	if x != nil {
		return x.Intents
	}
	return nil
}

func (x *PersonaResponse) GetTextModel() string {
	if x != nil {
		return x.TextModel
	}
	return ""
}

func (x *PersonaResponse) GetVisionModel() string {
	if x != nil {
		return x.VisionModel
	}
	return ""
}

type ListPersonasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonasRequest) Reset() {
	*x = ListPersonasRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonasRequest) ProtoMessage() {}

func (x *ListPersonasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonasRequest.ProtoReflect.Descriptor instead.
func (*ListPersonasRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{15}
}

type PersonaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonaInfo) Reset() {
	*x = PersonaInfo{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonaInfo) ProtoMessage() {}

func (x *PersonaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonaInfo.ProtoReflect.Descriptor instead.
func (*PersonaInfo) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *PersonaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonaInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PersonaInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PersonaInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListPersonasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personas      []*PersonaInfo         `protobuf:"bytes,1,rep,name=personas,proto3" json:"personas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonasResponse) Reset() {
	*x = ListPersonasResponse{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonasResponse) ProtoMessage() {}

func (x *ListPersonasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonasResponse.ProtoReflect.Descriptor instead.
func (*ListPersonasResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *ListPersonasResponse) GetPersonas() []*PersonaInfo {
	if x != nil {
		return x.Personas
	}
	return nil
}

var File_proto_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\">\n" +
	"\vChatRequest\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.gateway.v1.MessageR\bmessages\"O\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06images\x18\x03 \x03(\tR\x06images\"=\n" +
	"\fChatResponse\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.gateway.v1.MessageR\amessage\"\x12\n" +
	"\x10ListToolsRequest\"h\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\tR\x0finputSchemaJson\"Z\n" +
	"\x11ListToolsResponse\x12&\n" +
	"\x05tools\x18\x01 \x03(\v2\x10.gateway.v1.ToolR\x05tools\x12\x1d\n" +
	"\n" +
	"tools_json\x18\x02 \x01(\tR\ttoolsJson\"q\n" +
	"\x14ToolExecutionRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x94\x01\n" +
	"\x15ToolExecutionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12*\n" +
	"\x11execution_time_ms\x18\x04 \x01(\x03R\x0fexecutionTimeMs\"\x15\n" +
	"\x13ListMCPToolsRequest\"2\n" +
	"\bToolList\x12&\n" +
	"\x05tools\x18\x01 \x03(\v2\x10.gateway.v1.ToolR\x05tools\"\xcb\x01\n" +
	"\x14ListMCPToolsResponse\x12[\n" +
	"\x0ftools_by_server\x18\x01 \x03(\v23.gateway.v1.ListMCPToolsResponse.ToolsByServerEntryR\rtoolsByServer\x1aV\n" +
	"\x12ToolsByServerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.gateway.v1.ToolListR\x05value:\x028\x01\"\x80\x01\n" +
	"\x0fPersonaMetadata\x12!\n" +
	"\fpersona_name\x18\x01 \x01(\tR\vpersonaName\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"\x13\n" +
	"\x11GetPersonaRequest\"R\n" +
	"\fIntentConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\"\x9b\x02\n" +
	"\x0fPersonaResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"can_handle\x18\x04 \x03(\tR\tcanHandle\x12#\n" +
	"\rcannot_handle\x18\x05 \x03(\tR\fcannotHandle\x122\n" +
	"\aintents\x18\x06 \x03(\v2\x18.gateway.v1.IntentConfigR\aintents\x12\x1d\n" +
	"\n" +
	"text_model\x18\a \x01(\tR\ttextModel\x12!\n" +
	"\fvision_model\x18\b \x01(\tR\vvisionModel\"\x15\n" +
	"\x13ListPersonasRequest\"z\n" +
	"\vPersonaInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"K\n" +
	"\x14ListPersonasResponse\x123\n" +
	"\bpersonas\x18\x01 \x03(\v2\x17.gateway.v1.PersonaInfoR\bpersonas2\xe5\x03\n" +
	"\x0eGatewayService\x12;\n" +
	"\x04Chat\x12\x17.gateway.v1.ChatRequest\x1a\x18.gateway.v1.ChatResponse\"\x00\x12J\n" +
	"\tListTools\x12\x1c.gateway.v1.ListToolsRequest\x1a\x1d.gateway.v1.ListToolsResponse\"\x00\x12T\n" +
	"\vExecuteTool\x12 .gateway.v1.ToolExecutionRequest\x1a!.gateway.v1.ToolExecutionResponse\"\x00\x12S\n" +
	"\fListMCPTools\x12\x1f.gateway.v1.ListMCPToolsRequest\x1a .gateway.v1.ListMCPToolsResponse\"\x00\x12J\n" +
	"\n" +
	"GetPersona\x12\x1d.gateway.v1.GetPersonaRequest\x1a\x1b.gateway.v1.PersonaResponse\"\x00\x12S\n" +
	"\fListPersonas\x12\x1f.gateway.v1.ListPersonasRequest\x1a .gateway.v1.ListPersonasResponse\"\x00B\"Z gateway-service/proto/gateway/v1b\x06proto3"

var (
	file_proto_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_v1_gateway_proto_rawDescData []byte
)

func file_proto_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_gateway_proto_rawDesc), len(file_proto_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_v1_gateway_proto_rawDescData
}

var file_proto_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_gateway_v1_gateway_proto_goTypes = []any{
	(*ChatRequest)(nil),           // 0: gateway.v1.ChatRequest
	(*Message)(nil),               // 1: gateway.v1.Message
	(*ChatResponse)(nil),          // 2: gateway.v1.ChatResponse
	(*ListToolsRequest)(nil),      // 3: gateway.v1.ListToolsRequest
	(*Tool)(nil),                  // 4: gateway.v1.Tool
	(*ListToolsResponse)(nil),     // 5: gateway.v1.ListToolsResponse
	(*ToolExecutionRequest)(nil),  // 6: gateway.v1.ToolExecutionRequest
	(*ToolExecutionResponse)(nil), // 7: gateway.v1.ToolExecutionResponse
	(*ListMCPToolsRequest)(nil),   // 8: gateway.v1.ListMCPToolsRequest
	(*ToolList)(nil),              // 9: gateway.v1.ToolList
	(*ListMCPToolsResponse)(nil),  // 10: gateway.v1.ListMCPToolsResponse
	(*PersonaMetadata)(nil),       // 11: gateway.v1.PersonaMetadata
	(*GetPersonaRequest)(nil),     // 12: gateway.v1.GetPersonaRequest
	(*IntentConfig)(nil),          // 13: gateway.v1.IntentConfig
	(*PersonaResponse)(nil),       // 14: gateway.v1.PersonaResponse
	(*ListPersonasRequest)(nil),   // 15: gateway.v1.ListPersonasRequest
	(*PersonaInfo)(nil),           // 16: gateway.v1.PersonaInfo
	(*ListPersonasResponse)(nil),  // 17: gateway.v1.ListPersonasResponse
	nil,                           // 18: gateway.v1.ListMCPToolsResponse.ToolsByServerEntry
}
var file_proto_gateway_v1_gateway_proto_depIdxs = []int32{
	1,  // 0: gateway.v1.ChatRequest.messages:type_name -> gateway.v1.Message
	1,  // 1: gateway.v1.ChatResponse.message:type_name -> gateway.v1.Message
	4,  // 2: gateway.v1.ListToolsResponse.tools:type_name -> gateway.v1.Tool
	4,  // 3: gateway.v1.ToolList.tools:type_name -> gateway.v1.Tool
	18, // 4: gateway.v1.ListMCPToolsResponse.tools_by_server:type_name -> gateway.v1.ListMCPToolsResponse.ToolsByServerEntry
	13, // 5: gateway.v1.PersonaResponse.intents:type_name -> gateway.v1.IntentConfig
	16, // 6: gateway.v1.ListPersonasResponse.personas:type_name -> gateway.v1.PersonaInfo
	9,  // 7: gateway.v1.ListMCPToolsResponse.ToolsByServerEntry.value:type_name -> gateway.v1.ToolList
	0,  // 8: gateway.v1.GatewayService.Chat:input_type -> gateway.v1.ChatRequest
	3,  // 9: gateway.v1.GatewayService.ListTools:input_type -> gateway.v1.ListToolsRequest
	6,  // 10: gateway.v1.GatewayService.ExecuteTool:input_type -> gateway.v1.ToolExecutionRequest
	8,  // 11: gateway.v1.GatewayService.ListMCPTools:input_type -> gateway.v1.ListMCPToolsRequest
	12, // 12: gateway.v1.GatewayService.GetPersona:input_type -> gateway.v1.GetPersonaRequest
	15, // 13: gateway.v1.GatewayService.ListPersonas:input_type -> gateway.v1.ListPersonasRequest
	2,  // 14: gateway.v1.GatewayService.Chat:output_type -> gateway.v1.ChatResponse
	5,  // 15: gateway.v1.GatewayService.ListTools:output_type -> gateway.v1.ListToolsResponse
	7,  // 16: gateway.v1.GatewayService.ExecuteTool:output_type -> gateway.v1.ToolExecutionResponse
	10, // 17: gateway.v1.GatewayService.ListMCPTools:output_type -> gateway.v1.ListMCPToolsResponse
	14, // 18: gateway.v1.GatewayService.GetPersona:output_type -> gateway.v1.PersonaResponse
	17, // 19: gateway.v1.GatewayService.ListPersonas:output_type -> gateway.v1.ListPersonasResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_gateway_v1_gateway_proto_init() }
func file_proto_gateway_v1_gateway_proto_init() {
	if File_proto_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_gateway_proto_rawDesc), len(file_proto_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_v1_gateway_proto = out.File
	file_proto_gateway_v1_gateway_proto_goTypes = nil
	file_proto_gateway_v1_gateway_proto_depIdxs = nil
}
