events { worker_connections 1024; }

http {
    access_log /opt/homebrew/var/log/nginx/access.log;

    # Allow larger request bodies
    client_max_body_size 100M;
    client_body_buffer_size 10M;

    upstream go_orchestrator {
        server 127.0.0.1:9000;
    }

    server {
        listen 8080 http2; # Required for gRPC

        location /gateway.v1.GatewayService/Chat {
            grpc_pass grpc://go_orchestrator;
            grpc_read_timeout 300s;
            grpc_send_timeout 300s;
        }
    }
}